id: f5012a764f19411a8ab25f4e388f71a8
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_99-The_Blessed_One%27s_Wisdom_That_Leads_to_Infinite_Certainty-v2
  language: en
  author: ''
  volume: {}
